SRC = main.cpp
A = -D PARTA
D = -D OD
CFLAGS := `pkg-config opencv --cflags` `pkg-config opencv --libs`

a :
	g++ $(shell) $(SRC) $(CFLAGS) $(A) 
b :
	g++ $(shell) $(SRC) $(CFLAGS)
1d :
	g++ $(shell) $(SRC) $(CFLAGS) $(D)
