#include "opencv2/calib3d/calib3d.hpp"
#include "opencv2/imgproc/imgproc_c.h"
#include "opencv2/highgui/highgui_c.h"

#include <stdlib.h>
#include <stdio.h>

void remapAndDisparity(CvMat* l_remap0, CvMat* l_remap1, CvMat* r_remap0, CvMat* r_remap1)
{
    /* Variable initialization */
    CvArr *l_frame_remap = NULL;
    CvArr *r_frame_remap = NULL;
    CvArr *disparity_map = NULL;
    IplImage *l_frame = NULL;
    IplImage *r_frame = NULL;
    
    /* 
     * Open the goddamned webcams using dumbass C-API.
     * This is cv2.VideoCapture(id) in python
     */
    CvCapture *l_cap = cvCaptureFromCAM(1);
    CvCapture *r_cap = cvCaptureFromCAM(2);

    /* Time to remap the frames!!!! */
    while (1) {
        /* This is cap.read() in python */
        l_frame = cvQueryFrame(l_cap);
        r_frame = cvQueryFrame(r_cap);
    
        /* This is cv2.remap in python */
        cvRemap(l_frame, l_frame_remap, l_remap0, l_remap1, CV_INTER_LINEAR+CV_WARP_FILL_OUTLIERS, cvScalarAll(0));
        cvRemap(r_frame, r_frame_remap, r_remap0, r_remap1, CV_INTER_LINEAR+CV_WARP_FILL_OUTLIERS, cvScalarAll(0));

        /* This is cv2.stereoBM in python */
        CvStereoBMState *SBMS = cvCreateStereoBMState(CV_STEREO_BM_BASIC, 16);
        /* This is cv2.stereoBM.compute in python */
        cvFindStereoCorrespondenceBM(l_frame_remap, r_frame_remap, disparity_map, SBMS);

        /* 
         * Show the disparity map and waitkey.
         */
        cvShowImage("Image", disparity_map);
        key = cvWaitKey(10)&0xFF;
        if (key == 27 || key == 113 /* 113 is key 'q' */) {
            printf("Bye.\n");
            break;
        }
    }
    cvReleaseImage(&l_frame);
    cvReleaseImage(&r_frame);
    cvReleaseImage(&disparity_map);
}

void loadremap(CvMat* l_remap0, CvMat* l_remap1, CvMat* r_remap0, CvMat* r_remap1)
{
    /* 
     * Load remap information from saved remap.yml file,
     * which is generated by stereo calibration function from c++.
     * Because write a pure C-based one is too fucking stupid.
     */
    CvFileStorage *fs = cvOpenFileStorage("remap.yml", 0, CV_STORAGE_READ, NULL);
    l_remap0 = cvReadByName(fs, NULL, "left_remap0", NULL);
    l_remap1 = cvReadByName(fs, NULL, "left_remap1", NULL);
    r_remap0 = cvReadByName(fs, NULL, "right_remap0", NULL);
    r_remap1 = cvReadByName(fs, NULL, "right_remap1", NULL);
    if (l_remap0 == NULL || l_remap1 == NULL || r_remap0 == NULL || r_remap1 == NULL) {
        printf("what the fuck dude why is this happenening I hate my life.\n");
    }
}

int main (int argc, char** argv)
{
    /* Variable initializations, after all these years of python.... */
    int height = 7;
    int width = 10;
    char *p;

    CvMat *l_remap0 = NULL;
    CvMat *l_remap1 = NULL;
    CvMat *r_remap0 = NULL;
    CvMat *r_remap1 = NULL;

    /* Confirm height and weight */
    if (argc != 3) {
        printf("default height, width: 7, 10\n");
    } else {
        height = strtol(argv[1], &p, 10);
        width = strtol(argv[2], &p, 10);
        printf("height, width: %d, %d\n", height, width);
    }

    /* Load remap yaml */
    loadremap(l_remap0, l_remap1, r_remap0, r_remap1);

    /* Disparity go go go */
    remapAndDisparity(l_remap0, l_remap1, r_remap0, r_remap1);
    
    /* Deprecated test of Opencv C API */
    /*
    IplImage *gg = cvLoadImage("person.jpg", 1);
    
    cvShowImage("Image", gg);
    cvWaitKey(1);
    cvReleaseImage(&gg);
    */
    return 0;
}
